### ISSUE TITLE
Refine results front end

### ISSUE THREAD

**Issue by ghing** [openelections/openelections-core#168]
- [ ] Figure out if/how to represent data that will be available but isn’t ready yet
- [ ] Figure out what will live at the /results landing page. (see description below)
- [ ] Are different election bar densities a problem?
- [x] Fix spacing and scale to match spec (see [this comment](https://github.com/openelections/core/issues/168#issuecomment-49685237))
- [x] Results availability legend (see [this comment](https://github.com/openelections/core/issues/168#issuecomment-49685237))
- [x] Match legend colors (see [this comment](https://github.com/openelections/core/issues/168#issuecomment-49685237))
- [ ] Pink navigation arrows ((see [this comment](https://github.com/openelections/core/issues/168#issuecomment-49685237)))
- [x] Add table header "All Races year x - year y' (see [this comment](https://github.com/openelections/core/issues/168#issuecomment-49685237))
### Figure out what will live at the /results landing page

Since we're generating the results tables for each state client-side, a user will get the expected table and filter widgets if you visit a path like /results#md.  However if you visit /results, without the state hash, you get an empty table.  We need to decide what, if anything we want to show up for visitors to /results if no hash is specified.  Also, since there's a page template for the results page, Jekyll adds an entry for "Results" to the top nav bar.  I'm not sure if we want this or we want to suppress it, but it's definitely a problem if we don't have meaningful content rendered when no state is specified.
### Different election bar densities

![screenshot from 2014-07-17 14 43 54](https://cloud.githubusercontent.com/assets/110420/3618528/f8b76160-0dea-11e4-8c9a-9c188690cb8c.png)

![screenshot from 2014-07-17 14 44 34](https://cloud.githubusercontent.com/assets/110420/3618532/fe101990-0dea-11e4-8e15-33b87010f21d.png)
